#506 Improve checks for tabs and trailing whitespace

diff --git a/.github/workflows/ubuntu-infrastructure.yml b/.github/workflows/ubuntu-infrastructure.yml
--- a/.github/workflows/ubuntu-infrastructure.yml
+++ b/.github/workflows/ubuntu-infrastructure.yml
@@ -10,7 +10,7 @@ on:
       - develop
 
 jobs:
-  
+
   build-and-test:
 
     runs-on: ubuntu-24.04
@@ -54,4 +54,16 @@ jobs:
 
     - name: run infrastructure checks
       run: cmake --build . --target infrastructure
+      working-directory: chaste-build-dir
+      working-directory: chaste-build-dir
+
+    - name: run check for tabs and trailing whitespace
+      run: |
+        cmake --build . --target infrastructure_whitespace
+        if ! git diff --quiet --exit-code; then
+          echo "Error: check for tabs and trailing whitespace failed."
+          echo "Run python/infra/RemoveTabsAndTrailingWhitespace.py and commit the results."
+          git diff
+          exit 1
+        fi
       working-directory: chaste-build-dir
